### ISSUE TITLE
I3 config question 

### ISSUE THREAD

**Issue by Landixbtw** [hyper-dot/linuxfiles#1]
Is this an updated version of your older i3 dotfiles ? 
https://github.com/hyper-dot/dotfiles-old

Or something different, because I am currently trying to get your other config up and running because I really like it. But I cant get the rounded corners to work. Or to display the bar on my second monitor.

**Comment by hyper-dot** [comment]
No its not an updated version. Its different than older dots.
Yes it is my current dots. Its minimal and functional.

**Comment by Landixbtw** [comment]
Ok, thanks for the answer.
